services:
  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=demo"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=demo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
