spring.application.name=demo-app
spring.server.port=8080
server.servlet.context-path=/api/v1

# Database
spring.datasource.url=jdbc:postgresql://localhost:3306/demo_app_db
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=com.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.springframework=ERROR
logging.level.com.isyll.demo=INFO

app.security.jwtSecret=AO+IzEOa8l6XPHWayFiIGp6CgnivvibVqAbLV91//ARUdhjwCFXQiKHHz8sgtZyfXk6MSunyUoF/kDg2G5mUng==
app.security.jwtExpirationMs=86400000
