package com.example.demo.model.enums;

public enum AuditLogType {
  CLOSE_ACADEMIC_YEAR_EARLY,
  SUSPICIOUS_LOGIN,
  GRADE_MODIFIED_AFTER_FINALIZATION,
  STUDENT_DELETED,
  EXAM_SCHEDULE_CHANGED,
  UNAUTHORIZED_ACCESS_ATTEMPT,
  TEACHER_UNASSIGNED_FROM_CLASS,
  CLASSROOM_OVERBOOKED,
  ATTENDANCE_DATA_LOST,
  FILE_UPLOAD_FAILED
}
